package frc.robot.commands;

import frc.robot.subsystems.Drive;

import edu.wpi.first.wpilibj2.command.InstantCommand;

public class PrecisionToggle extends InstantCommand{
    public static Drive precisionDrive;
    public static boolean precisionToggle;

    public PrecisionToggle(Drive m_drive, boolean precision) {
        precisionDrive = m_drive;
        precisionToggle = precision;
        execute();
    }

    @Override
    public void initialize() {
    }

    @Override
    public void execute() {
        precisionToggle = !precisionToggle;
        precisionDrive.togglePrecisionTurnMode(precisionToggle);
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
